# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UseDotNet@2
  displayName: 'Use .NET Core runtime 5.0.6'
  inputs:
    packageType: runtime
    version: 5.0.6
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.8'
  inputs:
    versionSpec: 5.8
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '*/SevenDeadlySins/SevenDeadlySins.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: SevenDeadlySins'
  inputs:
    azureSubscription: 'Pay-As-You-Go (f49994cb-5581-4e57-9788-32a2f4a73b80)'
    WebAppName: SevenDeadlySins
